project:
  type: website

website:
  page-navigation: true
  favicon: "images/logo-ESA.png"
  title: "European Statistics Awards for Nowcasting"
  description: "Website of the INSEE team competing for the European Statistics Awards for Nowcasting, results and methods are freely-available and open-source."
  site-url: "https://inseefrlab.github.io/ESA-Nowcasting-2023/"
  
  repo-url: "https://github.com/InseeFrLab/ESA-Nowcasting-2023"
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#A7D5E8"
    right:
    - text: "License"
      href: LICENCE.md


  navbar:
    background: "#A7D5E8"
    logo: "images/logo-INSEE.png"
    align: center
    title: false
    collapse-below: lg
 
    right:
      - icon: github
        href: "https://github.com/InseeFrLab/ESA-Nowcasting-2023"
        aria-label: GitHub

    left:
      - text: "Overview"
        href: index.qmd
      - text: "Methodology"
        href: methodology.qmd
      - text: "Data"
        href: data.qmd
      - text: "GAS"
        href: gas.qmd
      - text: "OIL"
        href: oil.qmd
      - text: "ELECTRICITY"
        href: electricity.qmd
      - text: "Lessons Learned"
        href: lessons-learned.qmd
      - text: "Reproducibility"
        href: reproducibility.qmd
        
  sidebar:
    - id: gas
      title: "GAS"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: gas.qmd
        - href: post-mortem-gas.qmd

    - id: oil
      title: "OIL"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: oil.qmd
        - href: post-mortem-oil.qmd

    - id: electricity
      title: "ELECTRICITY"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: electricity.qmd
        - href: post-mortem-electricity.qmd

bibliography: biblio.bib 

format:
  html:
    theme:
      light: [cosmo, style/styles.scss]
    reference-location: margin
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    include-in-header: "style/fontawesome.html"

knitr:
  opts_knit:
    root.dir: "../"
  opts_chunk:    
    cache: true

execute:
  echo: false
  warning: false

freeze: auto

editor: visual